-- 예제 데이터베이스 생성
-- 테이블 삭제
DROP TABLE EMPLOYEE_T;
DROP TABLE DEPARTMENT_T;


-- 부서 테이블(DEPARTMENT_TBL) 생성
CREATE TABLE DEPARTMENT_T(
    DEPT_NO     NUMBER               NOT NULL,
    DEPT_NAME   VARCHAR2(15 BYTE)    NOT NULL,
    LOCATION    VARCHAR2(15 BYTE)    NOT NULL,
    CONSTRAINT PK_DEPT PRIMARY KEY(DEPT_NO)
);

-- 사원 테이블(EMPLOYEE_TBL) 생성
CREATE TABLE EMPLOYEE_T(
    EMP_NO      NUMBER              NOT NULL,
    NAME        VARCHAR2(20 BYTE)   NOT NULL,
    DEPART      NUMBER              NULL,
    POSITION    VARCHAR2(20 BYTE)   NULL,
    GENDER      CHAR(2 BYTE)        NULL,
    HIRE_DATE   DATE                NULL,
    SALARY      NUMBER              NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_NO),
    CONSTRAINT FK_DEPT_EMP FOREIGN KEY(DEPART) REFERENCES DEPARTMENT_TBL(DEPT_NO) ON DELETE SET NULL
);

INSERT INTO DEPARTMENT_T(DEPT_NO, DEPT_NAME, LOCATION) VALUES(1, '영업부', '대구');
INSERT INTO DEPARTMENT_T(DEPT_NO, DEPT_NAME, LOCATION) VALUES(2, '인사부', '서울');
INSERT INTO DEPARTMENT_T(DEPT_NO, DEPT_NAME, LOCATION) VALUES(3, '총무부', '대구');
INSERT INTO DEPARTMENT_T(DEPT_NO, DEPT_NAME, LOCATION) VALUES(4, '기획부', '서울');

